server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8000

salesforceConfiguration:
  name: Salesforce
  secret: "password"
  apiUrl: "http://localhost:8000/test/response"

companiesHouseConfiguration:
  name: CHIPS
  secret: "password"
  apiUrl: "http://localhost:8000/test/submission"
  barcodeServiceUrl: "http://localhost:8000/test/barcode"

jerseyClient:
  timeout: 10s
  connectionTimeout: 10s
  chunkedEncodingEnabled: false
  gzipEnabled: false
  gzipEnabledForRequests: false

log4jConfiguration:
  frequency: 1
  # Valid values are DAYS HOURS MICROSECONDS MILLISECONDS MINUTES NANOSECONDS SECONDS
  timeUnit: "HOURS"

testMode: false

logging:
  level: ${env.LOGGING_LEVEL!"DEBUG"}

fluentLogging:
  fluentLoggingOn: false
  tag: "forms-enablement-api"
  maxQueueSize: 20

# limit the submission of requests to x per second
rateLimit: ${env.RATE_LIMIT!1}