server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${env.PORT}

salesforceConfiguration:
  name: Salesforce
  secret: ${env.SALESFORCE_API_KEY}
  apiUrl: ${env.SALESFORCE_API_URL}

companiesHouseConfiguration:
  name: CHIPS
  secret: ${env.CHIPS_API_KEY}
  apiUrl: ${env.CHIPS_API_URL}
  barcodeServiceUrl: ${env.CHIPS_BARCODE_SERVICE_URL}

jerseyClient:
  timeout: 5000ms
  chunkedEncodingEnabled: false
  gzipEnabled: false
  gzipEnabledForRequests: false

log4jConfiguration:
  frequency: ${env.CH_LOG_FREQUENCY!"1"}
  # Valid values are DAYS HOURS MICROSECONDS MILLISECONDS MINUTES NANOSECONDS SECONDS
  timeUnit: ${env.CH_LOG_TIME_UNIT!"HOURS"}

logging:
  level: DEBUG
