server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: DEBUG

salesforceConfiguration:
  name: Salesforce
  secret: ${env.SALESFORCE_API_KEY!"ABC123"}
  apiUrl: ${env.SALESFORCE_API_URL!"www.example.com/submit"}

companiesHouseConfiguration:
  name: CHIPS
  secret: ${env.CHIPS_API_KEY!"ABC321"}
  apiUrl: ${env.CHIPS_API_URL!"https://fishandchips.herokuapp.com/chips"}
  barcodeServiceUrl: ${env.CHIPS_BARCODE_SERVICE_URL!"https://fishandchips.herokuapp.com/chips/barcode"}

jerseyClient:
  timeout: 5000ms
  chunkedEncodingEnabled: false
