server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8000

salesforceConfiguration:
  name: Salesforce
  secret: ${env.SALESFORCE_API_KEY!"ABC123"}
  apiUrl: ${env.SALESFORCE_API_URL!"www.example.com/submit"}

companiesHouseConfiguration:
  name: CHIPS
  secret: ${env.CHIPS_API_KEY!"ABC321"}
  apiUrl: ${env.CHIPS_API_URL!"http://localhost:8000/chips"}

