server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${env.PORT!8080}

salesforceConfiguration:
  name: Salesforce
  apiKey: ${env.SALESFORCE_API_KEY}
  authUrl: ${env.SALESFORCE_AUTH_URL}
  authGrantType: ${env.SALESFORCE_AUTH_TYPE}
  authUsername: ${env.SALESFORCE_AUTH_USERNAME}
  authPassword: ${env.SALESFORCE_AUTH_PASSWORD}
  authId: ${env.SALESFORCE_AUTH_ID}
  authSecret: ${env.SALESFORCE_AUTH_SECRET}
  clientUrl: ${env.SALESFORCE_CLIENT_URL}

companiesHouseConfiguration:
  name: CHIPS
  apiKey: ${env.CHIPS_API_KEY}
  chipsApiUrl: ${env.CHIPS_API_URL}
  barcodeServiceUrl: ${env.CHIPS_BARCODE_SERVICE_URL}
  presenterAuthUrl: ${env.CHIPS_PRESENTER_AUTH_URL}



jerseyClient:
  # The socket timeout value. If a read or write to the underlying
  # TCP/IP connection hasn't succeeded after this duration, a
  # timeout exception is thrown.
  timeout: ${env.TIMEOUT!"10s"}
  # The connection timeout value. If a TCP/IP connection cannot be
  # established in this time, a timeout exception is thrown.
  connectionTimeout: ${env.CONNECTION_TIMEOUT!"10s"}
  # Enables the use of chunked encoding for requests.
  chunkedEncodingEnabled: ${env.CHUNKED_ENCODING_ENABLED!"false"}
  # If true, the client will automatically decode response entities
  # with gzip content encoding.
  gzipEnabled: ${env.GZIP_ENABLED!"true"}
  # If true, the client will encode request entities with gzip
  # content encoding. (Requires gzipEnabled to be true).
  gzipEnabledForRequests: ${env.GZIP_ENABLED_FOR_REQUESTS!"true"}

log4jConfiguration:
  frequency: ${env.CH_LOG_FREQUENCY!1}
  # Valid values are DAYS HOURS MICROSECONDS MILLISECONDS MINUTES NANOSECONDS SECONDS
  timeUnit: ${env.CH_LOG_TIME_UNIT!"HOURS"}

testMode: false

logging:
  level: ${env.LOGGING_LEVEL!"DEBUG"}

fluentLogging:
  fluentLoggingOn: ${env.FLUENT_LOGGING_ON!"false"}
  fluentHost: ${env.FLUENT_HOST!"test"}
  fluentPort: ${env.FLUENT_PORT!20}
  tag: ${env.FORMS_API_LOG_TAG!"forms-enablement-api"}
  maxQueueSize: 20

# limit the submission of requests to x per second
rateLimit: ${env.RATE_LIMIT!1}
