server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

salesforceConfiguration:
  name: Salesforce
  secret: ${env.SALESFORCE_API_KEY!"ABC123"}
  apiUrl: ${env.SALESFORCE_API_URL!"www.example.com/submit"}

companiesHouseConfiguration:
  name: CHIPS
  secret: ${env.CHIPS_API_KEY!"ABC321"}
  apiUrl: ${env.CHIPS_API_URL!"http://demo7117990.mockable.io/chips-restService/rest/efilingEnablement/postForm"}
  barcodeServiceUrl: ${env.CHIPS_BARCODE_SERVICE_URL!"https://fishandchips.herokuapp.com/chips/barcode"}

jerseyClient:
  timeout: 5000ms
  chunkedEncodingEnabled: false
  gzipEnabled: false
  gzipEnabledForRequests: false

log4jConfiguration:
  frequency: ${env.CH_LOG_FREQUENCY!1}
  #Valid values are DAYS HOURS MICROSECONDS MILLISECONDS MINUTES NANOSECONDS SECONDS
  timeUnit: ${env.CH_LOG_TIME_UNIT!"HOURS"}

